include: package:effective_dart/analysis_options.1.3.0.yaml

analyzer:
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    lines_longer_than_80_chars: false
