name: dart_minecraft
description: Utilities for Minecraft and Mojang Web-APIs and reading/writing NBT Files. 
version: 0.3.3
homepage: https://github.com/spnda/dart_minecraft

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  uuid: ^3.0.4
  collection: ^1.15.0
dev_dependencies:
  effective_dart: ^1.3.0
  pedantic: ^1.10.0
  test: ^1.17.1

# analyzer:
#   - enable-experiment:
#     - non-nullable
