name: dart_minecraft
description: Utilities for Minecraft and Mojang Web-APIs and reading/writing NBT Files. 
version: 0.4.0
homepage: https://github.com/spnda/dart_minecraft

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  uuid: ^3.0.4
  collection: ^1.15.0
  http: ^0.13.3
dev_dependencies:
  path: ^1.8.0
  pedantic: ^1.11.1
  test: ^1.17.9

# analyzer:
#   - enable-experiment:
#     - non-nullable
