name: dart_minecraft
description: Utilities to access all Minecraft and Mojang APIs, including skins, name history and account management
version: 0.1.2+1
homepage: https://github.com/spnda/dart_minecraft

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  uuid: ^2.2.2
  path: ^1.7.0
dev_dependencies:
  pedantic: ^1.9.2
  effective_dart: ^1.3.0
  test: ^1.15.7
  collection: ^1.14.13

# analyzer:
#   - enable-experiment:
#     - non-nullable
