name: dart_minecraft
description: Utilities to access all Minecraft and Mojang APIs, including skins, name history and account management
version: 0.2.0
homepage: https://github.com/spnda/dart_minecraft

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  path: ^1.7.0
  uuid: ^2.2.2
dev_dependencies:
  collection: ^1.14.13
  effective_dart: ^1.3.0
  pedantic: ^1.9.2
  test: ^1.15.7

# analyzer:
#   - enable-experiment:
#     - non-nullable
