name: dart_minecraft
description: Utilities to access all Minecraft and Mojang APIs, including skins, name history and account management
version: 0.2.0
homepage: https://github.com/spnda/dart_minecraft

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.8.0
  uuid: ^3.0.0
dev_dependencies:
  collection: ^1.15.0
  effective_dart: ^1.3.0
  pedantic: ^1.10.0
  test: ^1.16.4

# analyzer:
#   - enable-experiment:
#     - non-nullable
